name: Manual CI

on: workflow_dispatch

permissions:
  contents: write

jobs:
  buid:
    runs-on: ubuntu-latest
    steps:
      - name: Install additional packages
        run: sudo apt-get install -y xorriso syslinux isolinux grub2-common grub-pc-bin grub-efi-ia32-bin grub-efi-amd64-bin
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Checkout submodules init
        run: git submodule init
      - name: Checkout submodules update
        run: git submodule update --remote
      - name: List dir content
        run: ls -la
      - name: Build Docker image
        run: ./build.sh
      - name: Publish release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*.img,dist/iso.iso"
          body: "Archlinux pxe images"
          tag: "v2.0.0"
